In [ ]:
import pandas as pd

excel_file = '/content/drive/MyDrive/FootballDummyData.xlsx'

sheet_name = 'PlayerTransfers'  

df = pd.read_excel(excel_file, sheet_name=sheet_name)
df.to_csv('playerTransfers.csv', index=False)

In [ ]:
pd.read_csv('matches.csv')

,MatchID,Date,HomeTeamID,AwayTeamID,HomeTeamScore,AwayTeamScore,Stadium,Referee
0,1,2023-11-06,5,12,2,1,Venice Field,Mark Clattenburg
1,2,2023-08-15,8,3,3,3,Marseille Ground,Mike Dean
2,3,2023-09-21,4,9,1,0,Napoli Park,Anthony Taylor
3,4,2023-10-11,7,10,0,2,Lyon Arena,Michael Oliver
4,5,2023-12-05,6,11,1,1,Paris Stadium,Martin Atkinson
...,...,...,...,...,...,...,...,...
205,206,2022-02-02,9,5,1,0,Bordeaux Park,Chris Johnson
206,207,2022-12-20,11,8,1,3,London Stadium,Michael Brown
207,208,2023-11-24,14,12,4,1,Chelsea Park,Michael Brown
208,209,2022-08-13,4,19,5,1,Napoli Park,David Smith
209,210,2021-07-03,18,4,5,2,Valencia Ground,Michael Jones

In [14]:
matches = pd.read_csv('playerStats.csv')
matches.isna().sum()

StatID             0
PlayerID           0
MatchID            0
Goals              0
Assists          399
YellowCards        0
RedCards           0
MinutesPlayed      0
dtype: int64

In [ ]:
matches.dtypes

MatchID           int64
Date             object
HomeTeamID        int64
AwayTeamID        int64
HomeTeamScore     int64
AwayTeamScore     int64
Stadium          object
Referee          object
dtype: object

In [1]:

transfer_history_df = pd.read_csv('playerTransfers.csv')  
players_df = pd.read_csv('players.csv')  

missing_players = transfer_history_df[~transfer_history_df['PlayerID'].isin(players_df['PlayerID'])]

print("\nPlayerIDs in transfer_history that don't exist in players:")
print(missing_players)

NameError: name 'pd' is not defined